package utils

import (
	"strings"
	"sync"
	"testing"
)

func TestGenerateShortKeyLength(t *testing.T) {
	key := GenerateShortKey()

	expectedLength := 6
	actualLength := len(key)

	if actualLength != expectedLength {
		t.Errorf("GenerateShortKey() produced a key of wrong length: got %d, want %d", actualLength, expectedLength)
	}
}

func TestGenerateShortKeyUniqueness(t *testing.T) {
	var wg sync.WaitGroup
	var keyMap sync.Map
	numGoroutines := 10
	keysPerGoroutine := 10000

	duplicateFound := make(chan struct{}, 1)


	for range numGoroutines {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for range keysPerGoroutine {
				key := GenerateShortKey()
				_, loaded := keyMap.LoadOrStore(key, true)
				if loaded {
					select {
					case duplicateFound <- struct{}{}:
					default:
					}
					return
				}
			}
		}()
	}

	wg.Wait()
	select {
	case <- duplicateFound:
		t.Fatal("Keys generated by GenerateShortKey() are not unique")
	default:
	}
}

func TestGenerateShortKeyCharset(t *testing.T) {
	k := GenerateShortKey()

	for _, r := range k {
		if !strings.ContainsRune(alphabet, r) {
			t.Errorf("GenerateShortKey() contains invalid char '%c'", r)
		}
	}
}